---
- name: Create CSR Routers
  hosts: localhost
  vars_files:
    - vars/csr_info.yml
  tasks:
    - name: Create base configs
      template:
        src: ./lab_base_configs/iosxe_config.txt.j2
        dest: './lab_base_configs/{{ item.hostname }}_config.txt'
        owner: root
        group: root
        mode: '0644'
      loop: "{{ csrs }}"

    - name: Create CSR image directories
      file:
        path: /var/lib/libvirt/images/{{ item.hostname }}
        state: directory
        mode: '0755'
      loop: "{{ csrs }}"

    - name: Create base config isos
      command: mkisofs -l -o /var/lib/libvirt/images/{{ item.hostname }}/csr_config.iso ./lab_base_configs/{{ item.hostname }}_config.txt
      loop: "{{ csrs }}"

    - name: Copy CSR ISO to specific CSR dirs
      copy:
        src: /var/lib/libvirt/images/{{ iso_name }}
        dest: /var/lib/libvirt/images/{{ item.hostname }}/{{ iso_name }}
        owner: qemu
        group: qemu
        mode: '0644'
      loop: "{{ csrs }}"

    - name: Create disk image for CSRs
      command: qemu-img create -f qcow2 /var/lib/libvirt/images/{{ item.hostname }}/csr_disk.qcow2 8G
      loop: "{{ csrs }}"

    - name: Create CSR VMs
      command: >
                virt-install \
                  --connect=qemu:///system \
                  --name={{ item.hostname }} \
                  --os-type=linux \
                  --os-variant=rhel4 \
                  --arch=x86_64 \
                  --cpu host
                  --vcpus=1,sockets=1,cores=1,threads=1 \
                  --hvm \
                  --ram=4096 \
                  --cdrom=/var/lib/libvirt/images/{{ item.hostname }}/{{ iso_name }}
                  --disk path=/var/lib/libvirt/images/{{ item.hostname }}/csr_disk.qcow2,bus=virtio,size=8,sparse=false,cache=none,format=qcow2 \
                  --disk path=/var/lib/libvirt/images/{{ item.hostname }}/csr_config.iso,device=cdrom,bus=ide \
                  --network bridge={{ item.int1_bridge }},model=virtio \
                  --noreboot
      loop: "{{ csrs }}"
    - name: Add additional interfaces
      command: >
                virsh attach-interface \
                  --domain {{ item[0] }} \
                  --type network \
                  --source {{ item[1] }} \
                  --model virtio \
                  --config 
      with_nested:
        - "{{ vms }}"
        - "{{ networks }}"
